sudo: required
dist: trusty
language: python
python: "2.7"

install:
   # Download a precompiled ROOT system
   - wget https://root.cern.ch/download/root_v6.14.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
   - tar -zxvf root_v6.14.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
   - . root/bin/thisroot.sh
   - time python -c 'from ROOT import kTRUE'
   # Install requirements
   - pip install -r requirements.txt
   - pip install pyflakes pycodestyle

script:
  # Static analysis
  - pyflakes mATLASplotlib
  - pycodestyle --statistics --ignore=E501 --count mATLASplotlib
  # Run package tests
  - py.test